sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.2
before_install: gem install bundler -v 2.0.1
script:
  - bundle exec rails db:drop RAILS_ENV=test
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec
