sudo: false
language: ruby
cache: bundler
rvm:
  - 2.6.2
before_install: gem install bundler -v 2.0.1
before_script:
  - psql -c 'create database business_market_test;' -U postgres
script:
  - bundle exec rspec
