default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: business_market_development

test:
  <<: *default
  database: business_market_test

production:
  <<: *default
  database: business_market_production
  username: business_market
  password: <%= ENV['BUSINESS_MARKET_DATABASE_PASSWORD'] %>
